<!DOCTYPE html>
<html class="lockscreen">
<head>
    <title>IMMS | Home</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ asset('packages/rydurham/sentinel/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/myStyle.css') }}">
</head>
<body>
<!--Wrapper-->
<div class="center">
    <div class="headline text-center" id="time">
        <!-- Time auto generated by js -->
    </div>
    <!-- /.headline -->
    <div>
        <h3 class="text-center"><img src="{{ asset('img/logo.png') }}"></h3>

        <div class="text-center">
            <a href="{{ route('view.home') }}"><img src="{{ asset('img/Student-logo.png') }}"></a>
            <a href="{{ route('Sentinel\login') }}"><img src="{{ asset('img/Admin-logo.png') }}"></a>
        </div>
    </div>

</div>
<script src="{{ asset('packages/rydurham/sentinel/js/jquery-2.0.2.min.js') }}"></script>
<script src="{{ asset('packages/rydurham/sentinel/js/bootstrap.min.js') }}"></script>
<script type="text/javascript">
    $(function () {
        startTime();
        $(".center").center();
        $(window).resize(function () {
            $(".center").center();
        });
    });

    /*  */
    function startTime() {
        var today = new Date();
        var h = today.getHours();
        var m = today.getMinutes();
        var s = today.getSeconds();

        // add a zero in front of numbers<10
        m = checkTime(m);
        s = checkTime(s);

        //Check for PM and AM
        var day_or_night = (h > 11) ? "PM" : "AM";

        //Convert to 12 hours system
        if (h > 12)
            h -= 12;

        //Add time to the headline and update every 500 milliseconds
        $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
        setTimeout(function () {
            startTime()
        }, 500);
    }

    function checkTime(i) {
        if (i < 10) {
            i = "0" + i;
        }
        return i;
    }

    /* CENTER ELEMENTS IN THE SCREEN */
    jQuery.fn.center = function () {
        this.css("position", "absolute");
        this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
            $(window).scrollTop()) - 30 + "px");
        this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
            $(window).scrollLeft()) + "px");
        return this;
    }
</script>
</body>